version: "3"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:${TAG}
    container_name: backend
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    depends_on:
      - backend
    restart: always
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80